var data = [
  { movieTitle: "Castle in the Sky", year: 1986, picture: "pic-1.jpg" },
  { movieTitle: "The Cat Returns", year: 2002, picture: "pic-2.jpg" },
  { movieTitle: "From Up on Poppy Hill", year: 2011, picture: "pic-3.jpg" },
  { movieTitle: "Grave of the Fireflies", year: 1988, picture: "pic-4.jpg" },
  { movieTitle: "Howl's Moving Castle", year: 2004, picture: "pic-5.jpg" },
  { movieTitle: "Kiki's Delivery Service", year: 1989, picture: "pic-6.jpg" },
  { movieTitle: "My Neighbor Totoro", year: 1988, picture: "pic-7.jpg" },
  {
    movieTitle: "Nausicaä of the Valley of the Wind",
    year: 1984,
    picture: "pic-8.jpg",
  },
  { movieTitle: "Only Yesterday", year: 1991, picture: "pic-9.jpg" },
  { movieTitle: "Pom Poko", year: 1994, picture: "pic-10.jpg" },
  { movieTitle: "Ponyo", year: 2008, picture: "pic-11.jpg" },
  { movieTitle: "Porco Rosso", year: 1992, picture: "pic-12.jpg" },
  { movieTitle: "Princess Mononoke", year: 1997, picture: "pic-13.jpg" },
  { movieTitle: "Spirited Away", year: 2001, picture: "pic-14.jpg" },
  { movieTitle: "The Boy and the Heron", year: 2023, picture: "pic-15.jpg" },
  {
    movieTitle: "The Secret World of Arrietty",
    year: 2010,
    picture: "pic-16.jpg",
  },
  {
    movieTitle: "The Tale of the Princess Kaguya",
    year: 2013,
    picture: "pic-17.jpg",
  },
  { movieTitle: "The Wind Rises", year: 2013, picture: "pic-18.jpg" },
  { movieTitle: "When Marnie Was There", year: 2014, picture: "pic-19.jpg" },
  { movieTitle: "Whisper of the Heart", year: 1995, picture: "pic-20.jpg" },
];
